packages:
  - '.'

overrides:
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  effect@<3.20.0: ^3.20.0
  postcss@<8.5.10: ^8.5.10
  vite: 7.3.5

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@vercel/speed-insights': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - effect@3.20.0
  - lodash@4.17.24
  - defu@6.1.5
  - vite@7.3.2
  - postcss@8.5.10
  - brace-expansion@5.0.6
  - js-cookie@3.0.6
  - esbuild@0.28.1
  - form-data@4.0.6
  - vite@7.3.5
  - '@babel/core@7.29.1'
  - js-yaml@4.1.2
