overrides:
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  '@babel/core': 7.29.6
  brace-expansion@1: 1.1.16
  brace-expansion@2: 2.1.2
  brace-expansion@5: 5.0.7
  defu: 6.1.5
  effect: 3.20.0
  js-cookie: 3.0.7
  js-yaml: 4.3.0
  lodash: 4.18.0
  postcss: 8.5.12
  sharp: 0.35.0

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
