name: Crawl and Upload Images

on:
  schedule:
    - cron: '0 */12 * * *'  
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: pnpm install
        
      - name: Crawl Images
        run: pnpm crawl
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  upload:
    needs: crawl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: pnpm install
        
      - name: Upload Images
        run: pnpm upload
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
